/* This code sample provides a starter kit to implement server side logic for your Teams App in JavaScript with code
 * snippets, refer to https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference for complete Azure
 * Functions developer guide.
 */

const ModsServerSdk = require('mods-server');

/**
 * This function handles requests sent from MODS Client SDK.
 * The HTTP request should contain an SSO token in the header and any content in the body.
 * The SSO token should be queried from Teams client by MODS Client SDK.
 * Before trigger this function, MODS binding would process the SSO token and generate MODS configuration.
 *
 * This function initializes the MODS Server SDK with the configuration and calls these APIs:
 * - getUserInfo() - Get the user's information from the received SSO token.
 * - getSqlConnection() - Establish a connection to the SQL Server,
 *                        according to the SQL endpoint configured in the function app settings.
 * - getMicrosoftGraphClientWithUserIdentity() - Get a graph client to access user's Microsoft 365 data.
 *
 * The response contains multiple message blocks constructed into a JSON object, including:
 * - An echo of the request body.
 * - The display name encoded in the SSO token.
 * - Information about SQL connection creation if SQL is enabled.
 * - Current user's Microsoft 365 profile if the user has consented.
 *
 * @param {Context} context - The Azure Functions context object.
 * @param {HttpRequest} req - The HTTP request.
 * @param {MODSConfig} config - The MODS configuration generated by MODS Binding.
 */
module.exports = async function (context, req, config) {
  context.log('JavaScript HTTP trigger function processed a request.');

  // Initialize response.
  const res = {
    status: 200,
    body: {}
  };

  // Put an echo into response body.
  res.body['receivedHTTPRequestBody'] = req.body || '';

  // Initialize MODS Server SDK with MODS configuration.
  let client;
  try {
    client = ModsServerSdk.MODS.getInstance(config);
  } catch(e) {
    context.log.error(e);
    res.status = 500;
    res.body = {
      error: 'Fail to initialize MODS Server SDK.'
    };
    return res;
  }

  // Query user's information from the authentication token.
  const currentUser = client.getUserInfo();
  if (currentUser && currentUser.displayName) {
    res.body['userInfoMessage'] = `User display name is ${currentUser.displayName}.`;
  } else {
    res.status = 400;
    res.body = {
      error: 'Fail to get user display Name.'
    };
    return res;
  }

  // Create a SQL connection to access data.
  try {
    const conn = await client.getSqlConnection();
    // Please add your code here.
    conn.close();
    res.body['SQLMessage'] = 'Successfully get SQL connection.';
  } catch (e) {
    context.log.error(e);
    res.status = 500;
    res.body = {
      error: 'Fail to get SQL connection.'
    };
    return res;
  }

  // Create a graph client to access user's Microsoft 365 data after user has consented.
  try {
    const graphClient = await client.getMicrosoftGraphClientWithUserIdentity(['.default']);
    const profile = await graphClient.api('/me').get();
    res.body['graphClientMessage'] = profile;
  } catch (e) {
    context.log.error(e);
    res.status = 500;
    res.body = {
      error: 'Fail to get profile, maybe consent flow is required.'
    };
    return res;
  }

  return res;
}